#!/bin/bash

# mixer bash
./mixer-settings

# midi connect
( /bin/sleep 10; 
  /usr/bin/aconnect p2600:0 "Pure Data":0
) &

# led setting server
./led-server.py &
ledpid=$!

if [ "$1" != "--gui" ]
then
  guiflag="-nogui"
else
  guiflag=""
fi

/usr/bin/pd $guiflag -alsamidi -mididev 0,1 -open _main.pd &
pdpid=$!

# trap exit and kill daemons
trap "kill $pdpid; kill $ledpid; trap - SIGTERM; exit" SIGTERM SIGINT EXIT

wait "$pdpid"
